import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" dir="rtl">

        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <header className="bg-zinc-950 p-6">

        </header>
        {children}
        <footer className="bg-zinc-950 p-6 h-32">

        </footer>
        </body>
        </html>
    );
}
